use client";

import { useState } from "react";
import { Upload, Play, Pause } from "lucide-react";

export default function Home() {
  const [videoURL, setVideoURL] = useState("");
  const [playing, setPlaying] = useState(false);

  const uploadVideo = (e) => {
    const file = e.target.files[0];
    if (file) {
      setVideoURL(URL.createObjectURL(file));
    }
  };

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <header className="h-16 border-b border-gray-800 flex items-center justify-between px-6">
        <h1 className="font-bold text-xl">MS Friend Editor</h1>
        <button className="bg-blue-600 px-5 py-2 rounded-lg">
          Publish
        </button>
      </header>

      <div className="grid grid-cols-12 h-[calc(100vh-64px)]">
        <aside className="col-span-3 border-r border-gray-800 p-5">
          <h2 className="text-lg mb-4">Components</h2>

          {["Text", "Image", "Button", "Section"].map((item) => (
            <button
              key={item}
              className="w-full bg-gray-800 p-3 rounded mb-3"
            >
              {item}
            </button>
          ))}

          <div className="mt-8">
            <h3 className="mb-3">Music Player</h3>

            <label className="flex items-center gap-2 bg-blue-600 p-3 rounded cursor-pointer">
              <Upload size={18} />
              Import Video Music

              <input
                type="file"
                accept="video/*"
                hidden
                onChange={uploadVideo}
              />
            </label>
          </div>
        </aside>

        <main className="col-span-6 p-8">
          <div className="bg-white text-black rounded-xl min-h-[600px] p-10">
            <h1 className="text-4xl font-bold">
              Build your website
            </h1>

            <p className="mt-5">
              Edit your design visually.
            </p>

            {videoURL && (
              <div className="mt-10">
                <video
                  src={videoURL}
                  controls
                  className="w-full rounded-lg"
                />

                <button
                  onClick={() => setPlaying(!playing)}
                  className="mt-3 bg-black text-white px-5 py-2 rounded flex gap-2"
                >
                  {playing ? <><Pause /> Pause Music</> : <><Play /> Play Music</>}
                </button>
              </div>
            )}
          </div>
        </main>

        <section className="col-span-3 border-l border-gray-800 p-5">
          <h2>Properties</h2>
          <div className="mt-5 bg-gray-900 p-4 rounded">
            Select an element to edit
          </div>
        </section>
      </div>

      <footer className="text-center py-5 border-t border-gray-800">
        Generated by Malik Mushahid
      </footer>
    </div>
  );
}
